resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: antrea-operator
  newName: antrea/antrea-operator
  newTag: v0.0.1-a535823.dirty
- name: antrea/antrea-operator
  newName: antrea/antrea-operator
  newTag: v0.0.1
- name: controller
  newName: antrea-operator
  newTag: latest
