name: Build and push latest image if needed

on:
  pull_request:
    branches:
      - merge_tgt
  push:
    branches:
      - merge_tgt

jobs:
  build:
    runs-on: [ubuntu-18.04]
    steps:
      - name: Test flags
        run: |
          echo "${{ github.event_name }}"
          echo "${{ github.event }}"
          echo "${{ github.event.pull_request }}"
          echo "${{ github.event.pull_request.merged }}"
          echo "${{ github.event.pull_request.merged == true }}"
